### PR TITLE
Pause & Resume

### PR DESCRIPTION
**Pull request by yemel**

### CODE REVIEW

**Review by fzavalia — COMMENTED** [review]
Hey!

Open Zeppelin provides a Pausable (PausableUpgradeable for this case) contract to handle this approach. I think it would be better to use that as auditors are already familiar with it.

**Comment by yemel** [comment]
I don’t know if the semantics are the same. Remember that the beneficiary
can still release the vested funds until the pause, so you need to store
the time stamp of the pause and not just a Boolean.

Also im not sure about the Upgradable part, we don’t want the vesting
contract to be upgradable AFIAK.

**Comment by fzavalia** [comment]
The "Upgradeable" contracts on Open Zeppelin only indicate that they are initializable instead of having things set in the constructor.

This is a requirement for contracts that run behind a proxy like this one.

**Comment by fzavalia** [comment]
We are already using the Pausable contract on other contracts. Manually implementing it might provide way to optimize gas minimally. But for standarization and reliability we should reuse these things.

**Comment by fzavalia** [comment]
This would be the implementation of the pause feature with only 1 timestamp and the OZ Pause contract https://github.com/decentraland/vestings-builder/pull/50

**Comment by yemel** [comment]
Hey @fzavalia!

Thanks for your answer, it's great to see progress on this front.

I understand the importance of reusing code that is already tested and familiar to auditors. Let's use the Pausable interface from OZ.

Having just one timestamp for both the revocation and the pause make sense. Remember that the vesting contract can be paused and then revoked. In that case the timestamp should stay the same.

> This is a requirement for contracts that run behind a proxy like this one.

Why do you say this contract is running behind a proxy? Current vesting contracts don't run behind a proxy AFAIK, check out this example: https://etherscan.io/address/0x0bb8270345bf29c2bb57c84e454830c4a0a6baf4#code

**Comment by fzavalia** [comment]
Etherscan is smart enough to just show you the code of the contract but what is deployed with the factory is just a minimal proxy pointing to the implementation contract which is https://etherscan.io/address/0x42f32e19365d8045661a006408cc6d1064039fbf#code

image

**Comment by fzavalia** [comment]
This is done to make it cheaper for the deployer as only a really small contract that delegates all calls to the implementation contract is deployed

**Comment by yemel** [comment]
Good to know, thank you for the explanation. Closing this!

**Pull request closed without merging**
